### ISSUE TITLE
Hola, no puedo loguearme en tu web, no llega el mail!!!

### ISSUE THREAD

**Issue by Lennoxae** [ReinierTutoriales/ReinierTutoriales#1]
como estas?. consulta, me podrias ayudar a conseguir el link de macOS 13.2.1, 
quiero loguearme en tu foro pero no me llega el mail

desde ya muchas gracias por tus tutoriales,
sos un genio,
gracias!

**Comment by ReinierTutoriales** [comment]
pasa por telegram
